version: '3.7'

services:
  lam-validator-api:
    container_name: lam-validator-api
    build:
      context: ..
      dockerfile: ./docker/validator/api/Dockerfile
    ports:
      - ${RDF_VALIDATOR_API_PORT}:${RDF_VALIDATOR_API_PORT}
    env_file: .env
    restart: always
    networks:
      - mydefault

  lam-validator-ui:
    container_name: lam-validator-ui
    build:
      context: ..
      dockerfile: ./docker/validator/ui/Dockerfile
    ports:
      - ${RDF_VALIDATOR_UI_PORT}:${RDF_VALIDATOR_UI_PORT}
    env_file: .env
    restart: always
    depends_on:
      - "lam-validator-api"
    networks:
      - mydefault

  lam-generation-service-api:
    container_name: lam-generation-service-api
    build:
      context: ..
      dockerfile: ./docker/lam4doc/api/Dockerfile
    ports:
      - ${LAM_API_PORT}:${LAM_API_PORT}
    env_file: .env
    restart: always
    networks:
      - mydefault

  lam-generation-service-ui:
    container_name: lam-generation-service-ui
    build:
      context: ..
      dockerfile: ./docker/lam4doc/ui/Dockerfile
    ports:
      - ${LAM_UI_PORT}:${LAM_UI_PORT}
    env_file: .env
    restart: always
    depends_on:
      - "lam-generation-service-api"
    networks:
      - mydefault

  fuseki:
    container_name: lam-fuseki
    image: meaningfy/fuseki:latest
    volumes:
      - lam-fuseki:/fuseki
    env_file: .env
    environment:
      - ADMIN_PASSWORD=${LAM_FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${LAM_FUSEKI_JVM_ARGS}
    ports:
      - ${LAM_FUSEKI_EXTERNAL_PORT}:3030
    networks:
      - mydefault

volumes:
  lam-fuseki:

networks:
  mydefault:
    name: globalnet