version: '3.7'

services:
  lam-validator-api:
    container_name: lam-validator-api
    build:
      context: ..
      dockerfile: ./docker/validator/api/Dockerfile
    volumes:
      - ..:/usr/src/app
    ports:
      - ${RDF_VALIDATOR_API_PORT}:${RDF_VALIDATOR_API_PORT}
    env_file: ../.env
    restart: always
    depends_on:
      - rdf-validator-celery-worker
    networks:
      - mydefault

  lam-validator-ui:
    container_name: lam-validator-ui
    build:
      context: ..
      dockerfile: ./docker/validator/ui/Dockerfile
    volumes:
      - ..:/usr/src/app
    ports:
      - ${RDF_VALIDATOR_UI_PORT}:${RDF_VALIDATOR_UI_PORT}
    env_file: ../.env
    restart: always
    depends_on:
      - lam-validator-api
    networks:
      - mydefault

  rdf-validator-celery-worker:
    container_name: rdf-validator-celery-worker
    build:
      context: ..
      dockerfile: ./docker/validator/api/Dockerfile
    command: celery -A validator.adapters.celery.celery_worker worker -Q validator_tasks
    volumes:
      - ..:/usr/src/app
    env_file: ../.env
    networks:
      - mydefault
    depends_on:
      - rdf-validator-redis

  rdf-validator-redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - ${RDF_VALIDATOR_REDIS_PORT}:${RDF_VALIDATOR_REDIS_PORT}
    networks:
      - mydefault

  validator-dashboard:
    build:
      context: ..
      dockerfile: ./docker/validator/api/Dockerfile
    command: celery -A validator.adapters.celery.celery_worker --broker=${RDF_VALIDATOR_REDIS_LOCATION}:${RDF_VALIDATOR_REDIS_PORT} flower --port=${RDF_VALIDATOR_FLOWER_PORT}
    ports:
      - ${RDF_VALIDATOR_FLOWER_PORT}:${RDF_VALIDATOR_FLOWER_PORT}
    depends_on:
      - rdf-validator-celery-worker
    networks:
      - mydefault

  lam-generation-service-api:
    container_name: lam-generation-service-api
    build:
      context: ..
      dockerfile: ./docker/lam4doc/api/Dockerfile
    volumes:
      - ..:/usr/src/app
      - lam-reports:/tmp/lam_reports
    ports:
      - ${LAM_API_PORT}:${LAM_API_PORT}
    env_file: ../.env
    restart: always
    networks:
      - mydefault
    depends_on:
      - lam-generation-celery-worker

  lam-generation-service-ui:
    container_name: lam-generation-service-ui
    build:
      context: ..
      dockerfile: ./docker/lam4doc/ui/Dockerfile
    volumes:
      - ..:/usr/src/app
    ports:
      - ${LAM_UI_PORT}:${LAM_UI_PORT}
    env_file: ../.env
    restart: always
    depends_on:
      - "lam-generation-service-api"
    networks:
      - mydefault

  lam-generation-celery-worker:
    container_name: lam-generation-celery-worker
    build:
      context: ..
      dockerfile: ./docker/lam4doc/api/Dockerfile
    command: celery -A lam4doc.adapters.celery.celery_worker worker --loglevel=info -Q lam4doc_tasks
    volumes:
      - ..:/usr/src/app
      - lam-reports:/tmp/lam_reports
    env_file: ../.env
    networks:
      - mydefault
    depends_on:
      - rdf-validator-redis
      - fuseki

  fuseki:
    container_name: lam-fuseki
    image: stain/jena-fuseki:5.1.0
    volumes:
      - lam-fuseki:/fuseki
    env_file: ../.env
    environment:
      - ADMIN_PASSWORD=${LAM_FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${LAM_FUSEKI_JVM_ARGS}
      - FUSEKI_DATASET_2=lam
    user: "root"
    ports:
      - ${LAM_FUSEKI_EXTERNAL_PORT}:3030
    networks:
      - mydefault

volumes:
  lam-fuseki:
  lam-reports:

networks:
  mydefault:
    name: globalnet